// src/components/Skills.vue
<script setup lang="ts">
import Card from "primevue/card";
import Tag from "primevue/tag";
import { ref } from "vue";

const techSkills = ref([
  { icon: "fa-brands fa-python", name: "Python" },
  { icon: "fa-brands fa-js", name: "Javascript/Typescript" },
  { icon: "fa-brands fa-react", name: "React" },
  { icon: "fa-brands fa-vuejs", name: "Vue" },
  { icon: "fa-solid fa-code", name: "Django/DRF" },
  { icon: "fa-brands fa-git-alt", name: "Git" },
  { icon: "fa-solid fa-screwdriver-wrench", name: "Esbuild" },
  { icon: "fa-solid fa-database", name: "PostgreSQL" },
  { icon: "fa-brands fa-docker", name: "Docker" },
  { icon: "fa-solid fa-chart-simple", name: "Scikit-Learn" },
  { icon: "fa-solid fa-code", name: "Celery" },
  { icon: "fa-brands fa-node-js", name: "Nodejs" },
]);

const softSkills = ref([
  { icon: "fa-brands fa-python", name: "Analytical" },
  { icon: "fa-brands fa-js", name: "Adaptable" },
  { icon: "fa-brands fa-react", name: "Team player" },
  { icon: "fa-brands fa-vuejs", name: "Problem solver" },
  { icon: "fa-brands fa-vuejs", name: "Curious about learning" },
]);
</script>
<template>
  <div id="skills" class="grid w-screen align-items-start p-4 surface-50">
    <div id="title-group col-12">
      <p class="name-title my-2">Skills</p>
    </div>
    <div class="grid col-12">
      <div class="col-12 md:col-6">
        <Card>
          <template #title>Technical skills</template>

          <template #content>
            <div class="flex flex-wrap gap-1">
              <Tag v-for="item in techSkills" :value="item.name">
                <template #icon>
                  <font-awesome-icon
                    :icon="item.icon"
                    slot="icon"
                    class="mr-1"
                  ></font-awesome-icon>
                </template>
              </Tag>
            </div>
          </template>
        </Card>
      </div>
      <div class="col-12 md:col-6">
        <Card>
          <template #title>Soft skills</template>
          <template #content>
            <div class="flex flex-wrap gap-1">
              <Tag v-for="item in softSkills" :value="item.name">
                <template #icon>
                  <font-awesome-icon
                    :icon="item.icon"
                    slot="icon"
                    class="mr-1"
                  ></font-awesome-icon>
                </template>
              </Tag>
            </div>
          </template>
        </Card>
      </div>
    </div>
  </div>
</template>

<style>
.name-title {
  font-family: "Inter";
  letter-spacing: 2px;
  font-size: 54px;
}
.image {
  clip-path: circle();
}
</style>

// portfolio-frontend/app/components/sections/Skills.tsx
import { Section } from "@/types/navbar";
import React from "react";
import SkillCard from "../cards/SkillCard";
import SectionWrapper from "./SectionWrapper";

import {
  faDocker,
  faGitAlt,
  faJs,
  faNodeJs,
  faPython,
  faReact,
  faVuejs,
} from "@fortawesome/free-brands-svg-icons";
import {
  faBook,
  faBrain,
  faChartSimple,
  faChessKnight,
  faCircleNodes,
  faCode,
  faComments,
  faDatabase,
  faPeopleGroup,
  faScrewdriverWrench,
} from "@fortawesome/free-solid-svg-icons";

import { Skills as SkillsType } from "@/types/skills";
import SkillsContainer from "../cards/SkillsContainer";

const techSkills: SkillsType = [
  { icon: faPython, label: "Python" },
  { icon: faJs, label: "JS/TS" },
  { icon: faReact, label: "React" },
  { icon: faVuejs, label: "Vue" },
  { icon: faCode, label: "Django/DRF" },
  { icon: faGitAlt, label: "Git" },
  { icon: faScrewdriverWrench, label: "Esbuild" },
  { icon: faDatabase, label: "PostgreSQL" },
  { icon: faDocker, label: "Docker" },
  { icon: faChartSimple, label: "SKLearn" },
  { icon: faCode, label: "Celery" },
  { icon: faNodeJs, label: "Nodejs" },
];

const softSkills: SkillsType = [
  { icon: faChartSimple, label: "Analytical" },
  { icon: faCircleNodes, label: "Adaptable" },
  { icon: faPeopleGroup, label: "Team player" },
  { icon: faBrain, label: "Problem solver" },
  { icon: faBook, label: "Curious about learning" },
  { icon: faChessKnight, label: "Business acumen" },
  { icon: faComments, label: "Communicative" },
];

const Skills = () => {
  return (
    <SectionWrapper id={Section.Skills} className="h-full" title="Skills">
      <div className="h-full grid grid-cols-1 md:grid-cols-2 gap-8">
        <SkillsContainer title="Technical Skills">
          {techSkills.map((skill) => {
            return (
              <SkillCard
                key={skill.label}
                label={skill.label}
                icon={skill.icon}
              />
            );
          })}
        </SkillsContainer>
        <SkillsContainer title="Soft Skills">
          {softSkills.map((skill) => {
            return (
              <SkillCard
                key={skill.label}
                label={skill.label}
                icon={skill.icon}
              />
            );
          })}
        </SkillsContainer>
      </div>
    </SectionWrapper>
  );
};

export default Skills;
